//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.DataAccess
{
    public partial class drug
    {
        public string brandname { get; set; }
        public string genericname { get; set; }
        public string manufacturer { get; set; }
        public string price { get; set; }
        public string quantity { get; set; }
        public int id { get; set; }
        public string pre { get; set; }
    }
}
