//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.DataAccess
{
    public partial class patient
    {
        public string name { get; set; }
        public string address { get; set; }
        public string m1 { get; set; }
        public string m2 { get; set; }
        public string docassociated { get; set; }
        public string drugassociated { get; set; }
        public string sym { get; set; }
        public string teaspoon { get; set; }
        public int id { get; set; }
        public string times { get; set; }
        public System.DateTime date { get; set; }
        public string pharmname { get; set; }
        public string rx { get; set; }
    }
}
